### ISSUE TITLE
Update to Drupal 7.35

### ISSUE THREAD

**Issue by funkyfuture** [samos123/docker-tutum-drupal#9]
I already got it working. I will test it tomorrow again and push then.

**Comment by samos123** [comment]
Ok I will create tags and update docker registry after you've pushed.

**Comment by funkyfuture** [comment]
Fixed by fc17031

**Comment by funkyfuture** [comment]
btw, my guess now would be that drush wanted to inform about the available security update per mail when it fails with 7.34.

**Comment by cerisier** [comment]
Can't wait for new tag =)

**Comment by samos123** [comment]
Created a new tag and triggered new build.

On Sat, Mar 21, 2015 at 12:55 AM, Corentin Kerisit <notifications@github.com
